"""Initial migration

Revision ID: 8d267ad4c563
Revises: 3d7485aa5a6e
Create Date: 2024-01-12 18:32:41.368968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d267ad4c563'
down_revision = '3d7485aa5a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('filters_headcount')
    op.drop_table('filters_geography')
    op.drop_table('filters_storage')
    op.drop_table('filters_function')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters_function',
    sa.Column('function_name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('filters_storage',
    sa.Column('geography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('headcount', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('function', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('filters_geography',
    sa.Column('geography_name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('filters_headcount',
    sa.Column('headcount_name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_bought', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    # ### end Alembic commands ###
